### ISSUE TITLE
error on redirect

### ISSUE THREAD

**Issue by ehsandam** [DNNCommunity/DNN.Vendors#6]
after clicking on banner get this error 

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

**Requested URL: /xxx/DesktopModules/Admin/Banners/BannerClickThrough.aspx**

vendor version : 8
dnn version : 8.0.2

**Comment by kgoods** [comment]
Hi,
Since no one else has answered...
The BannerClickThoughPage in BannerController.cs is still pointing to the old path "/Desktopmodules/Admin/Banners/BannerClickThrough.aspx" see code in link below on line 45. The path should be "/DesktopModules/Vendors/BannerClickThrough.aspx"

If you don't have access to Visual Studio to re-compile let me know and I'll get you a copy of my modified Dnn.Modules.Vendors.dll 

Here's the link to the code in question (line 45)
[https://github.com/DNNCommunity/DNN.Vendors/blob/master/src/Dnn.Modules.Vendors/Components/BannerController.cs](url)

Hope this helps.

**Comment by bislamovic** [comment]
I do not have access to VS - can you send it?

**Comment by kgoods** [comment]
[Dnn.Modules.Vendors.zip](https://github.com/DNNCommunity/DNN.Vendors/files/420600/Dnn.Modules.Vendors.zip)

Unzip this one to the  bin folder replacing the one that's currently there and you should be good to go.

Kind regards,
Ken

BTW, the link to the code doesn't work any longer so if anyone is looking for it just open that file in the repository.

**Comment by bislamovic** [comment]
Site crashed when I upload it. Then when I bring back old .dll site was down.
So I restarted App Pool and everything is working normaly.
Should I reset AppPool when upload your .dll? Is it normal?

**Comment by kgoods** [comment]
Did you happen to get any kind of error message? The only thing I can think of is maybe you're missing the external references that the maintainer just added to this branch three days ago. I already had them since I have upgraded all the way from DNN 6.0. I've never tried from a clean install of DNN 8.

Try a restart of IIS after the new dll is uploaded and if it still crashes put it back and view the error log and see if it mentions any missing dlls. 

The ones in question are DotNetNuke.Web.Depreciated.dll, DotNetNuke.WebControls.dll, and Telerik.Web.UI.dll. Alternatively, you could go into your bin folder and see if those are there. If not, they need to be. 

But I'm still leaning towards it being an issue with IIS needing a restart, although, theoretically it shouldn't. 

Let me know how you get on and if I can be of more help.

**Comment by bislamovic** [comment]
Ok - as web is live I need to wait until next night for update :)

**Comment by joannschlosser** [comment]
If the BannerClickThrough.aspx page doesn't even exist - and I have loaded and removed and reloaded and looked at the source code and still cannot find this page - how would I get my hands on it and get it into place since the Install.zip file isn't doing it?

**Comment by kgoods** [comment]
I took a look at mine and noticed that the BannerClickThrough.aspx file had a time/date stamp the day after all the others. I must have moved that file from the old path (Admin/Banners) to the new path (DesktopModules/Vendors) when I was trying to get this to work. I just looked at the install zip and you are correct, it doesn't appear to be included. 
As I said before, I never tried to install this on a new DNN installation, I've been using it since DNN 6 and it broke when I upgraded to DNN 8 since it was removed from the base install. It's been so long since I fixed it that I don't really remember how much I had to do to get it to work but I did remember that I had to recompile the dll due to the bad path to BannerClickThough.aspx.

Here's the file I'm using successfully. It needs to go into the DesktopModules/Vendors folder.

Hope it helps, let me know.

[BannerClickThrough.zip](https://github.com/DNNCommunity/DNN.Vendors/files/435148/BannerClickThrough.zip)

Note: You'll also need the recompiled dll posted earlier in this thread which fixes the bad path. I'm still not sure if you need the other dlls I mentioned above as I haven't heard back from bislamovic yet.

**Comment by kgoods** [comment]
Now that I look a little closer I notice that the code behind (BannerClickThrough.aspx.cs) is also missing except I still have it in DesktopModules/admin/Banners. I'm not sure if it's still somehow referencing the old code behind file or how it's even working.

What needs to happen is someone needs to do a clean install of DNN 8 then install this module then figure out what needs to happen to make it work. I don't have any extra time right now but I might be able to get to it in a week or two. My experience has been only with an upgrade to DNN 8 so I already had the Banners module installed. It just broke when I did the upgrade to DNN 8 and I only did what was necessary to get it to work for me. And it does work 100% as I use it daily.

Sorry but I don't think I can be of much more help here.

**Comment by joannschlosser** [comment]
Well, I have it running fine on a DNN7 site, maybe I just copy that stuff over?  My DNN8 installs are all clean, out of the box, with a clean install of DNN8's vendors module, so. . .  I wonder if it will even let me install it older version on the DNN8 site so I can do the upgrade.  Will try later.  Thanks for looking at this.

**Comment by SteveCowling** [comment]
I made a cheap and dirty fix here, I created a folder in in Admin called Banners and pasted the BannerClickThrough.aspx inside restarted the App Pool and it works perfectly.

**Comment by roman-yagodin** [comment]
Fixed installer: https://github.com/roman-yagodin/DNN.Vendors/releases/tag/v8.0.0-update.1
